server:
  port: 8081
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  mvc:
    favicon:
      enabled: false
  mail:
    host: smtpdm.aliyun.com
    username: ys@p00q.cn
    password: 123123
    default-encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://danmu:123@39.108.110.44:27017/dm
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    druid:
      url: jdbc:mysql://10.0.91.46:3306/ys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
      username: 123
      password: 123
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 10.0.91.46
    port: 6379
    timeout: 10000
    password: 123
mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
logging:
  path: "./logs/"
  file: "./logs/dbys.log"
  file.max-size: 100MB
dbys:
  mail-sender: "ys@p00q.cn"